all: 
	g++ -std=c++11 -O3 -Wall p.cpp -lm

s:
	g++ -std=c++11 -O3 -Wall -fsanitize=address p.cpp -lm
gerador:
	 g++ -std=c++11 -O3 -Wall ladrilho_valido.cpp -lm -o gerador
run:
	./a.out

runx:
	./a.out < tests/p1_testeX.txt

runy:
	./a.out < tests/p1_testeY.txt

runz:
	./a.out < tests/p1_testeZ.txt

runw:
	./a.out < tests/p1_testeW.txt

runa:
	./a.out < tests/p1_testeA.txt

runb:
	./a.out < tests/p1_testeB.txt

runc:
	./a.out < tests/p1_testeC.txt

1:
	./a.out < tests/1

2:
	./a.out < tests/2

3:
	./a.out < tests/3

4:
	./a.out < tests/4

5:
	./a.out < tests/5

6:
	./a.out < tests/6
		
7:
	./a.out < tests/7

8:
	./a.out < tests/8

9:
	./a.out < tests/9
		
10:
	./a.out < tests/10

11:	
	./a.out < tests/11

12:
	./a.out < tests/12

13:
	./a.out < tests/13

14:
	./a.out < tests/14

15:
	./a.out < tests/15
16:
	./a.out < tests/16
17:
	./a.out < tests/17
18:
	./a.out < tests/18
19:
	./a.out < tests/19
20:
	./a.out < tests/20
22:
	./a.out < tests/22


clean:
	rm -f *.o p
